Talend/components

- components-splunk/pom.xml
if we skip integration tests we don't need docker plugin execution on pre-integration-test and post-integration-test phase. Used skipITs as the parameter for skipping plugin execution.
> TDI-35766: skip docker plugin execution on skipITs.

- components-api/src/main/java/org/talend/components/api/properties/ComponentPropertiesImpl.java
- components-api/src/main/java/org/talend/components/api/properties/ComponentPropertyFactory.java
- components-api/src/main/resources/org/talend/components/api/properties/ComponentPropertiesImpl.properties
- components-api/src/test/java/org/talend/components/api/properties/ComponentPropertiesTest.java
WIP
https://jira.talendforge.org/browse/TCOMP-202
Also return properties display names  should be removed from all components. But currently I can't check it in Studio, because of old component-api version in Studio (0.11.0)
> TCOMP-202 Added display names for common returns properties

- components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java
- components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceComponentTestIT.java
https://jira.talendforge.org/browse/TDI-35987
Because the query mode in tSalesforceInput can control "bulk connection" or not.
So we can set the value of bulkConnection based on query mode.
> TDI-35987: Hide "Use HTTP Chunked" for tSalesforceInput Bulk Query

- components-dataprep/src/main/java/org/talend/components/dataprep/connection/DataPrepConnectionHandler.java
- components-dataprep/src/main/java/org/talend/components/dataprep/runtime/DataSetWriter.java
- components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepConnectionHandlerTest.java
- components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepServerMock.java
* Adds close() method for DataPrepConnectionHandler responsible of flush & close.
* Don't flush at every line for better efficiency.
* Update unit test so test now ensure all content is send to service.
> Output stream usage fixes

- components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceAvroRegistry.java
- components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceAvroRegistryTest.java
SalesforceAvroRegistry returns String schema for Percent Salesforce specific data type
SalesforceAvroRegistry returns Double schema for Percent Salesforce specific data type
Related to https://jira.talendforge.org/browse/TDI-37479
> TDI-37479 Added percent type schema infering

- components-filedelimited/src/main/java/org/talend/components/filedelimited/FileDelimitedDefinition.java
- components-filedelimited/src/main/java/org/talend/components/filedelimited/tfileinputdelimited/TFileInputDelimitedDefinition.java
- components-filedelimited/src/main/java/org/talend/components/filedelimited/tfileoutputdelimited/TFileOutputDelimitedDefinition.java
- components-filedelimited/src/test/java/org/talend/components/filedelimited/FileDelimitedTestIT.java
1. Schema can't propagate tFileOutputDelimited automatically.
_isSchemaAutoPropagate()_ for tFileOutputDelimited should return true.
2. Based on old framework configuration xml. For tFileOutputDelimited :
_isConditionalInputs()_ should return _false_ and _getPartitioning()_ should return **NONE** not **AUTO**
Fix above issue and add unit test.
> fix (TDI-37671): wrong configuration in tfileoutputdelimited definition

- components-filedelimited/src/main/java/org/talend/components/filedelimited/runtime/DelimitedAdaptorFactory.java
- components-filedelimited/src/main/java/org/talend/components/filedelimited/runtime/DelimitedReader.java
- components-filedelimited/src/test/java/org/talend/components/filedelimited/runtime/FileDelimitedReaderTestIT.java
The number lines count of tFileInputDelimited no-csv mode is incorrect
fix with correct count
> fix (TDI-37593): tfileinputdelimited no-csv mode wrong nb line count

- services/components-api-service-rest-all-components/pom.xml
Current Docker image names provided by Maven (with maven-docker-plugin) are using an hardcoded name for the Talend private registry & they do not include the Git branch name.
Now Docker image names are using the 'talend_docker_registry' as the registry name in prefix & the git branch name as a suffix.
This allows integration of these docker images in Talend CI.
> feat(DEVOPS-1225): parametrize Docker image name with git branch

- components-dataprep/src/main/java/org/talend/components/dataprep/connection/DataPrepConnectionHandler.java
- components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepConnectionHandlerTest.java
- components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepServerMock.java
don't encode the username and password value in the url
encode the username and password value in the url
[Data Prep components] Listiing Preparations or Datasets fails if the user's password contains special chars
https://jira.talendforge.org/browse/TDI-37748
> TDI-37748: [Data Prep components] Listiing Preparations or Datasets

- components-jdbc/src/main/java/org/talend/components/jdbc/datastore/JDBCDatastoreDefinition.java
- components-jdbc/src/main/resources/org/talend/components/jdbc/datastore/messages.properties
https://jira.talendforge.org/browse/TCOMP-367
add the lost display name in the message file for data store
https://jira.talendforge.org/browse/TCOMP-367
> fix(TCOMP-367): Add display name for tJDBCDatastore

- components-jdbc/src/main/java/org/talend/components/jdbc/CommonUtils.java
- components-jdbc/src/main/java/org/talend/components/jdbc/dataset/JDBCDatasetProperties.java
- components-jdbc/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
- components-jdbc/src/test/java/org/talend/components/jdbc/dataprep/JDBCDatasetTestIT.java
https://jira.talendforge.org/browse/TCOMP-379
https://jira.talendforge.org/browse/TCOMP-379
> fix(TCOMP-379): fix the getSample method for JDBCDatasetRuntime, make it can works when no schema found in the dataset properties

- components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/helpers/FilterExpressionTable.java
- components/components-azurestorage/src/test/java/org/talend/components/azurestorage/table/AzureStorageTableComponentsTest.java
- components/components-azurestorage/src/test/java/org/talend/components/azurestorage/table/helpers/FilterExpressionTableTest.java
please refer to : https://jira.talendforge.org/browse/TDI-38338
the boolean type is available in the filter expression table and can be used to construct filters
> fix(TDI-38338): add boolean type to filter expressions table

- components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/runtime/AzureStorageTableWriter.java
- components/components-azurestorage/src/test/java/org/talend/components/azurestorage/table/runtime/TAzureStorageOuputTableTestIT.java
https://jira.talendforge.org/browse/TDI-38302
No need to set the azure table entity property when the record value is null.
> fix(TDI-38302): fix NPE in azure table writer when record value is null

- components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/tazurestorageinputtable/TAzureStorageInputTableProperties.java
- components/components-azurestorage/src/test/java/org/talend/components/azurestorage/table/runtime/AzureStorageTableBaseTestIT.java
- components/components-azurestorage/src/test/java/org/talend/components/azurestorage/table/runtime/TAzureStorageInputTableTestIT.java
table
https://jira.talendforge.org/browse/TDI-38356
we keep the order as is in the azure table
> fix(TDI-38356): keep the order of the dynamic schema as is in azure

- components/components-bigquery/bigquery-integration/pom.xml
`bigquery-integration` fails due to annotation processing when compiling, due to an excluded guava dependency.
`bigquery-integration` compiles and tests run successfully.
> fix: do not exclude transitive guava dependencies for integration test.

- components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/helpers/SupportedFieldType.java
- components/components-azurestorage/src/test/java/org/talend/components/azurestorage/table/helpers/FilterExpressionTableTest.java
https://jira.talendforge.org/browse/TDI-38459
we removed the int64 and binary types from azure filter table. those types are not used
> fix(TDI-38459): remove INT64 and binary types form azure filter table

- components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/runtime/AzureStorageTableWriter.java
the feedback collections need to be initialized before each write operation
https://jira.talendforge.org/browse/TDI-38493
the feedback collections need to be initialized before each write operation
> fix(TDI-38493): fix the azure table writer feedback

- components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataset/SalesforceDatasetProperties.java
- components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
- components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
- components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceBulkQueryReader.java
- components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSource.java
- components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDatasetRuntime.java
- components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/dataprep/SalesforceInputTestIT.java
https://jira.talendforge.org/browse/TDI-38488
* SalesforceDataset component was making useless connection
* Activate compression
* Handle wait for batch differently: start to sleep only if can't fetch
first and retry again.
*  make the waiting for salesforce batch result "smarter"
We start to wait 2 seconds for 5 attempt then we multiply the wait time by 2 until the result is returned or a timeout is occurred.
* Remove of non existing resource load. this was slowing the initialize() method of SalesforceDataprepSource for no reason because the file *salesforce.properties* dose not exist
**What kind of change does this PR …
> fix(TDI-38488): improve response time of SalesforceDataset component

- components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/dataset/JDBCDatasetProperties.java
- components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
- components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
- components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/dataprep/JDBCDatasetRuntime.java
- components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
https://jira.talendforge.org/browse/TDI-38041
we add the read-only option for the jdbc connection setting.
the data set have to be in a read-only mode for dataprep to deny queries that try to alter data or schemas
this will allow only read statement to be executed with the JDBC connection
this is also a hint to the driver to enable database optimizations
> feature(TDI-38041): protect from SQL injection in TCOMP/JDBC component

- components/components-azurestorage/src/main/java/org/talend/components/azurestorage/wizard/AzureStorageComponentListProperties.java
https://jira.talendforge.org/browse/TDI-38700
the user can finish the wizard at any point and this cause some schema lo be lost
We force the user to go through all wizard pages to preserve the already selected schema
> fix(TDI-38700): Azure storage wizard can't save schema which was checked

- components/components-fileio/simplefileio-runtime/src/main/java/org/apache/beam/sdk/io/hdfs/ConfigurableHDFSFileSink.java
- components/components-fileio/simplefileio-runtime/src/main/java/org/apache/beam/sdk/io/hdfs/ConfigurableHDFSFileSource.java
- components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sinks/ConfigureWithSampleHDFSWriter.java
- components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sinks/UgiFileSinkBase.java
- components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sources/UgiFileSourceBase.java
- components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/ugi/UgiDoAs.java
The spec required the keytab to be installed on every worker node in the cluster, which is impractical for some clients.  Applying this patch causes the HDFS delegation token to be created on the driver for the principal/keytab and serialized to the nodes where it is reconstituted for all HDFS actions.
Since tokens are never reused with this system, it should also fix TCOMP-422
TCOMP-422 (Delegation tokens expire on the TCOMP after a timeout of ~24 hours).
TFD-1241 (Keytabs must be installed on every worker node in the cluster).
HDFS delegation token to be created on the driver for the principal/keytab and serialized to the nodes where it is reconstituted for all HDFS actions. …
> fix(TFD-1241): Don't require keytab on worker nodes for fileio (maintenance/0.18)

- tooling/IDEs/eclipse/codetemplates.xml
year is hard coded into the copyright
make the year auto generated in eclipse
> fix(copyright-year): make the copyright year automated in eclipse

- components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceAvroRegistryString.java
- components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/dataprep/SalesforceAvroRegistryStringTest.java
* filter out only salesforce picklist fields with a parent
Salesforce picklist fields that have a parent (compound name) are not supported by salesforce bulk API.
Salesforce picklist fields that have a parent (compound name) are filtered out
> bugfix(TDP-3980)_filter_picklist_fields_with_parent

- components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataset/SalesforceDatasetProperties.java
- services/components-api-service-rest/src/main/java/org/talend/components/service/rest/impl/PropertiesControllerImpl.java
- services/components-api-service-rest/src/main/java/org/talend/components/service/rest/impl/PropertiesHelpers.java
- services/components-api-service-rest/src/test/java/org/talend/components/service/rest/fullexample/FullExampleComponentTestIT.java
- services/components-api-service-rest/src/test/java/org/talend/components/service/rest/fullexample/dataset/FullExampleDatasetProperties.java
- services/components-api-service-rest/src/test/resources/org/talend/components/service/rest/fullexample/dataset/messages.properties
rest api and salesforce had a refreshProperties method, a kind of callback that was created has created especially for DP to have some properties initialized after a datastore is set.
There is no more custom method but rather using a standard callback (trigger) concept for this behavior.
depends on https://github.com/Talend/daikon/pull/246
> feat(TDKN-167):remove refreshProperties and added ref after callback

- components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceModuleProperties.java
- components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputPropertiesTest.java
Component throws exception then something wrong with connection properties (expired password, etc.)
User should check error log to see the reason 
Component return ValidationResult.Result.ERROR, so user could see error immediately
> fix(TDI-39014): Show error frame instead of throw Exception

- core/components-adapter-beam-parent/pom.xml
- core/components-adapter-beam/pom.xml
- core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/TCompBoundedSourceAdapter.java
- core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/TCompSinkAdapter.java
- core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/coders/LazyAvroCoder.java
- core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/coders/LazyAvroCoderProviderRegistrar.java
- core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/gcp/GcpServiceAccountOptions.java
- core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/gcp/ServiceAccountCredentialFactory.java
- core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/io/rowgenerator/RowGeneratorIO.java
- core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/transform/ConvertToIndexedRecord.java
- core/components-adapter-beam/src/test/java/org/talend/components/adapter/beam/io/rowgenerator/RowGeneratorIOTest.java
- core/components-adapter-beam/src/test/java/org/talend/components/adapter/beam/transform/ConvertToIndexedRecordTest.java
- examples/components-api-archetypes/poc-bd-archetype/src/main/resources/archetype-resources/__componentNameLowerCase__-runtime__runtimeVersionConverted__/pom.xml
- examples/components-api-archetypes/poc-bd-archetype/src/main/resources/archetype-resources/__componentNameLowerCase__-runtime__runtimeVersionConverted__/src/main/java/runtime__runtimeVersionConverted__/__componentNameClass__DatasetRuntime.java
- examples/components-api-archetypes/poc-bd-archetype/src/main/resources/archetype-resources/__componentNameLowerCase__-runtime__runtimeVersionConverted__/src/main/java/runtime__runtimeVersionConverted__/__componentNameClass__OutputRuntime.java
- services/components-api-service-rest-all-components/pom.xml
- services/components-maven-repo/pom.xml
* Upgrade to Beam 2.0 for all base repo in TCOMP
* small API changes
* CoderRegistry changes, no setFallBack support, use AutoService to registry provider, 
* IndexedRecord as the only accept type between components, if component need other coder, provide themself
* No Sink API in beam anymore, TCompSinkAdapter is not used for the moment, will see if ParDo/DoFn can cover all the situation for component usage when there is a real example. (or it can be removed actually)
! ALL individual components change will be in next PR.
If this PR …
> feat(TFD-1591): Upgrade beam adapter in TCOMP with beam 2.0

- components/components-kafka/kafka-definition/src/main/java/org/talend/components/kafka/dataset/KafkaDatasetProperties.java
- components/components-pubsub/pubsub-definition/src/main/java/org/talend/components/pubsub/PubSubDatasetProperties.java
the PubSub and the Kafka components are using a simple input field to let the user define AVSC.
Since the AVSC are a multi-line format, creating them is not user friendly
Change the property to use ACE.
> feat(TFD-2413): Use ACE editor on AVSC defintiion.

- components/components-bigquery/bigquery-definition/src/main/java/org/talend/components/bigquery/output/BigQueryOutputProperties.java
- components/components-bigquery/bigquery-definition/src/test/java/org/talend/components/bigquery/output/BigQueryOutputPropertiesTest.java
- components/components-bigquery/bigquery-runtime/src/main/java/org/talend/components/bigquery/runtime/BigQueryOutputRuntime.java
- components/components-bigquery/bigquery-runtime/src/test/java/org/talend/components/bigquery/runtime/BigQueryBeamRuntimeTestIT.java
- components/components-kafka/kafka-definition/src/main/java/org/talend/components/kafka/dataset/KafkaDatasetProperties.java
- components/components-pubsub/pubsub-definition/src/main/java/org/talend/components/pubsub/PubSubDatasetProperties.java
The BigQueryOutput use the metadata schema to put its data into BigQuery. This is not compatible with TFD.
The BigQueryOuput will infer the schema from the data.
> Bugfix/TFD-2421 Infer the schema from the incoming data

- components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSinkTestIT.java
- components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java
- components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceGetDeletedUpdatedReader.java
- components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceRuntime.java
- components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
- components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/SObjectAdapterFactoryTest.java
- components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/SalesforceRuntimeTest.java
Compare to old framework, salesforce lose RawOffset and DSTSavings when write date to salesforce with timezone.
Keep same behavior with old framework.
For issue : https://jira.talendforge.org/browse/TDI-39582
> fix(TDI-39582): tSalesforceOutput set invalid dates

- components-parent/pom.xml
- services/components-api-service-rest-all-components/pom.xml
- services/components-api-service-rest/pom.xml
The component PreparationRow is going to need some new widget definition that are only available on daikon 0.20.0-SNAPSHOT.
Components is now using daikon 0.20.0-SNAPSHOT.
> Change Daikon version to 0.20.0-SNAPSHOT.

- components/components-kafka/kafka-runtime/src/main/java/org/talend/components/kafka/runtime/KafkaOutputPTransformRuntime.java
Kafka output dataset avro schema is inferred from the incoming data, and the dataset's user defined avro schema is not used. 
Use user supplied schema as output schema for kafak output avro dataset.
> fix(TFD-3920) : use supplied avro schema in kafka dataset

- components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/ConfigurableHDFSFileSink.java
When writing a Streaming pane to a file, a NPE can occur if there are no records in the pane.
When writing a Streaming pane to a file, panes without records are silently ignored.
> fix(rskraba): Don't write files for empty streaming panes.

- components/components-fileio/s3-runtime-di/pom.xml
- components/components-fileio/s3-runtime-di/src/main/java/org/talend/components/s3/runtime/S3Connection.java
- components/components-fileio/s3-runtime-di/src/test/java/org/talend/components/s3/runtime/PropertiesPreparer.java
- components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3DatasetProperties.java
- components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3Region.java
- components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3RegionUtil.java
- components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/s3/S3DatasetPropertiesTest.java
- components/components-fileio/simplefileio-runtime/pom.xml
- components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3Connection.java
- components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3DatasetRuntime.java
- components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/s3/S3DatasetRuntimeTestIT.java
- components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/s3/S3DatastoreRuntimeTestIT.java
- components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/s3/S3TestResource.java
https://jira.talendforge.org/browse/TDI-40107
https://jira.talendforge.org/browse/TDI-40107
> fix(TDI-40107): show all buckets whatever region they are in and remove the region properties, fetch the region by the bucket name at runtime

- components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputDefinition.java
- components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputProperties.java
- components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputDefinitionTest.java
- components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputPropertiesTest.java
https://jira.talendforge.org/browse/TDI-37641
Update schema may not have Id field.
Delete schema may contain more than 1 field - Id.
Id field always present for Update action except dynamic schema.
Delete action contains only 1 field - Id
Changes only for design part.
> fix(TDI-37641): add ID field for Update and Delete actions

- components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
See https://jira.talendforge.org/browse/TCOMP-931
* Make use of setReadOnly() resilient to unsupported Hive features.
* See https://jira.talendforge.org/browse/TCOMP-931 for details.
> fix(TCOMP-931): Add support for Hive

- components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
https://jira.talendforge.org/browse/TDI-40793
Hive jdbc setRadOnly JDBC method throws SQLException and we only catch SQLFeatureNotSupportedException on that call.
We catch SQLException 
Don't know if there is breaking change.
> fix(TDI-40793) : Catch SQLException on jdbc setReadOnly call

- components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistry.java
- components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeSourceOrSink.java
- core/components-common/src/main/java/org/talend/components/common/avro/JDBCAvroRegistry.java
https://jira.talendforge.org/browse/TDI-43612
Added functionality that escapes the underscores and remove escapes before underscores in object names. Now tables and schemas that have the symbol "_" in their names can be obtained from Snowflake.
> fix(TDI-43612): Handling underscores in Snowflake objects names

- components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeDbTypeProperties.java
- components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputPropertiesTest.java
* set empty list as default value for the custom db types: column and dbtype properties
https://jira.talendforge.org/browse/TDI-41286
use an empty list as a default value instead of null value
> fix(TDI-41286): set default values

- core/components-common/src/main/java/org/talend/components/common/tableaction/DefaultSQLCreateTableAction.java
- core/components-common/src/test/java/org/talend/components/common/tableaction/DefaultSQLCreateTableActionTest.java
What is the current behavior? (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-44578
What is the new behavior?
First the dbType used is first the one from advanced settings, then after the one from studio schema (shuld be empty for tcompV0, but we have the in migration it seems).
> fix(TDI-44578) : dbType conf over dbType in schema

- components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
- components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.properties
previously there was an weird message. https://jira.talendforge.org/browse/TDI-36042 
The message is user-friendly now.
works well in TOS_DI-20210101_1939-V7.4.1 with components-parent version0.29.0-SNAPSHOT
Was added the try/catch block in the SalesforceSourceOrSink and error.connectionFail in the properties. Have no idea why the error.expiredPassword was deleted and added again it was not being …
> fix(TDI-36042): Friendly connection error message

- components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReaderTestIT.java
- components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkV2ExecReader.java
For JIRA: https://jira.talendforge.org/browse/TDI-45526
> fix(TDI-45526):tSalesforceOutputBulkExec using Bulk V2 crashes when zero

- core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/io/rowgenerator/GeneratorFunction.java
This task is to switch the Beam GeneratorFunction to use SHA-256 instead of MD5. It is only being used for test-code, but we might as well eliminate MD5 as it is a deprecated algorithm.
> TDI-46133 - Switch Beam GeneratorFunction to use SHA-256 instead of MD5

- components-parent/components-bom/pom.xml
https://jira.talendforge.org/browse/TDI-47935
Backport of https://github.com/Talend/components/pull/2079 into "maintenance/8.0" branch.
> fix(TDI-47935): bump "nimbus-jose-jwt" lib to fix CVE.

- services/components-api-service-rest/src/main/resources/application.properties
Even if the management probe is by default running on the same port as the application, the user can choose to comment out the configuration parameter and use a different port.
The default port chosen was `9000`, which was already used by another component of the TDP on-prem install. So, let's switch to an unused one.
> fix(TDP-11227): change default mgmt port to an unused one
