Talend/components

components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceRuntime.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputProperties.java
components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceComponentTestIT.java

https://jira.talendforge.org/browse/TCOMP-77
Note:Fix enum property with String value can't work in runtime.

TCOMP-77: New tSalesforceOutput doesn't work

---

components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceComponentTestIT.java

related  to https://github.com/Talend/daikon/pull/8

removed children from Form, widget list is enougth

---

components-api/src/main/java/org/talend/components/api/component/IVirtualComponentDefinition.java
components-api/src/main/java/org/talend/components/api/properties/IVirtualComponentProperties.java

https://jira.talendforge.org/browse/TCOMP-117

TCOMP-117:  Add interface of virtual component

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceAvroRegistry.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceAvroRegistryTest.java

1. complete built-in Avro type

---

components-api/src/main/java/org/talend/components/api/component/VirtualComponentDefinition.java
components-api/src/main/java/org/talend/components/api/properties/VirtualComponentProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReaderTestIT.java

https://jira.talendforge.org/browse/TCOMP-141
1)Change the interface of virtual component
2)Add implement in tSalesforceOutputBulkExec

TCOMP-141: Change the virtual component interface and add the implement in salesforce

---

components-api/src/main/java/org/talend/components/api/properties/ComponentReferenceProperties.java

TCOMP-151 referenceType is a enum type

TCOMP-151 referenceType is a enum type

---

components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceOutputProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecProperties.java

https://jira.talendforge.org/browse/TUP-4452

TUP-4452: fix the migratask issues for salesforce bulk components

---

components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforcegetservertimestamp/TSalesforceGetServerTimestampProperties.java
components-salesforce/src/main/resources/org/talend/components/salesforce/tsalesforcegetservertimestamp/messages.properties

https://jira.talendforge.org/browse/TUP-4405
Add advanced setting for tSalesforceGetServerTimestamp

TUP-4405: No property on the Advanced settings tab for tSalesforceGetServerTimestamp

---

components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceBulkProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceOutputProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulk/TSalesforceOutputBulkProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java
components-salesforce/src/main/resources/org/talend/components/salesforce/tsalesforceoutputbulk/messages.properties

https://jira.talendforge.org/browse/TDI-35932

TDI-35932: fix the ui for salesforce bulk components

---

components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceOutputProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulk/TSalesforceOutputBulkProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java

https://jira.talendforge.org/browse/TDI-35910

TDI-35910: add the miss value for upsert relation table

---

components-common/src/main/java/org/talend/components/common/runtime/BulkFileWriter.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulk/TSalesforceOutputBulkDefinition.java

https://jira.talendforge.org/browse/TUP-4476

TUP-4476: Runtime issue for tSalesforceOutputBulkExec:Bulk file path

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceGetDeletedUpdatedReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceInputReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceServerTimeStampReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceSource.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceServerTimeStampReaderTestIT.java

1)Salesforce input bulk query "use exists connection"
https://jira.talendforge.org/browse/TUP-4426
2)Salesforce inclued delete records
https://jira.talendforge.org/browse/TUP-4430
3) Get updated/deleted records issue
https://jira.talendforge.org/browse/TUP-4457
4) get server time NPE
https://jira.talendforge.org/browse/TDI-35955

TUP-4426: Salesforce runtime issue

---

components-splunk/src/test/java/org/talend/components/splunk/runtime/TSplunkEventCollectorWriterTestIT.java

Extended DefaultComponentRuntimeContainer to use in tests.

TDI-35766: Used DefaultComponentRuntimeContainer instead of implementing interface.

---

components-api/src/main/java/org/talend/components/api/exception/DataRejectException.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java

https://jira.talendforge.org/browse/TUP-4428

TUP-4428: Handle reject record in component side.

---

components-common/src/main/java/org/talend/components/common/BulkFileProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java

Output schema can be different
https://jira.talendforge.org/browse/TUP-4491

TUP-4491: Need to add another schema for components which Input and

---

components-salesforce/src/main/resources/org/talend/components/salesforce/SalesforceConnectionProperties.properties
components-salesforce/src/main/resources/org/talend/components/salesforce/SalesforceModuleListProperties.properties

https://jira.talendforge.org/browse/TUP-4395

TUP-4395: Fixed missing i18n for wizard

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceAvroRegistry.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkFileWriter.java

salesforce bulk components
https://jira.talendforge.org/browse/TUP-4480

TUP-4480: fix upsert with relation tables and dynamic schema for

---

components-common/src/main/java/org/talend/components/common/runtime/BulkFileWriter.java
components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceConnectionModuleProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceOutputProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkFileWriter.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceGetDeletedUpdatedReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceInputReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceSource.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulk/TSalesforceOutputBulkProperties.java
components-salesforce/src/main/resources/org/talend/components/salesforce/SalesforceConnectionModuleProperties.properties

https://jira.talendforge.org/browse/TCOMP-154
Add return value for salesforce

TCOMP-154: Add return the return value for salesforce input/output components

---

components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/connection/oauth/SalesforceOAuthConnection.java

https://jira.talendforge.org/browse/TCOMP-71

TCOMP-71: Improve component OAuth connection

---

components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java

https://jira.talendforge.org/browse/TUP-4514

TUP-4514: fix the proxy show_if issue

---

components-common/src/main/java/org/talend/components/common/runtime/BulkFileWriter.java

https://jira.talendforge.org/browse/TUP-4480

TUP-4480: fix the dynamic for tsalesforceouputbulk

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java

https://jira.talendforge.org/browse/TUP-4513
Fixed runtime part of tSalesforceOutput upsert relationship

TUP-4513: Fix upsert relation don't work in upsert action for tSalesforceOutput

---

components-api/src/main/java/org/talend/components/api/exception/DataRejectException.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java

component(tsalesforcebulkexec)
https://jira.talendforge.org/browse/TUP-4547

TUP-4547: support reject line for input

---

components-common/src/main/java/org/talend/components/common/runtime/BulkFileWriter.java
components-common/src/main/java/org/talend/components/common/runtime/GenericAdapterFactory.java
components-common/src/main/java/org/talend/components/common/runtime/GenericAvroRegistry.java
components-common/src/test/java/org/talend/components/common/runtime/BulkFileWriterTest.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkFileWriter.java

https://jira.talendforge.org/browse/TUP-4512
This modification not a final one. Need to refactor later.

TUP-4512: Add a generic format

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SObjectAdapterFactory.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceInputReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceSchemaConstants.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java

https://jira.talendforge.org/browse/TUP-4544

TUP-4544: Add support foreign key in SOQL for tSalesforceInput

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SObjectAdapterFactory.java

https://jira.talendforge.org/browse/TUP-4544

TUP-4544: Remove useless code.

---

components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceConnectionModuleProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceModuleProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/UpsertRelationTable.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforcegetservertimestamp/TSalesforceGetServerTimestampProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulk/TSalesforceOutputBulkProperties.java
components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceComponentTestIT.java
components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceRuntimeTestUtil.java
components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceTestBase.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkFileWriterTestIT.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkLoadTestIT.java

junit to test the tsalesforceoutputbulk
https://jira.talendforge.org/browse/TUP-4480

TUP-4480: add a new method to replace Form constructor and add some

---

components-splunk/pom.xml
components-splunk/src/test/java/org/talend/components/splunk/runtime/TSplunkEventCollectorWriterTestIT.java

Added docker maven plugin to run container with splunk image. It will be started on pre-integration-test phase and stopped and removed on post-integration-test phase.
Defined a system property in pom.xml to be used in integration tests. Removed Ignore annotation from integration tests to run them during build.

TDI-35766: added docker plugin for integration tests.

---

components-splunk/src/main/java/org/talend/components/splunk/TSplunkEventCollectorDefinition.java

Added automatic schema propagation to tSplunkEventCollector component.

TDI-36223: Fixed automatic schema synchronization.

---

components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceRuntimeTestUtil.java
components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceTestBase.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java

missing
https://jira.talendforge.org/browse/TUP-4508

TUP-4508: TUP-4428  Handle reject record in component side. JUNIT

---

components-common/src/main/java/org/talend/components/common/BulkFileProperties.java

https://jira.talendforge.org/browse/TUP-4769

TUP-4769: NB_Line type issue for salesforceOutputBulk

---

components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceOutputProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java

https://jira.talendforge.org/browse/TUP-4770

TUP-4770: salesforceOutputBulkExec upsert key column field type changed

---

components-dataprep/src/main/resources/org/talend/components/dataprep/tdatasetinput/messages.properties

NPE is fixed by the studio team.
Dataset Name -> Dataset ID

TDI-36316: tDataSetInput ask for dataset name, but expect its ID

---

components-dataprep/src/main/java/org/talend/components/dataprep/tdatasetinput/TDataSetInputProperties.java
components-dataprep/src/test/java/org/talend/components/dataprep/tdatasetinput/TDataSetInputDefinitionAndPropertiesTest.java

Remove double quotes handling in design time due to fix in the studio.

TDI-36400: Remove double quotes

---

components-api/src/main/java/org/talend/components/api/service/ComponentService.java
components-api/src/main/java/org/talend/components/api/service/internal/ComponentServiceImpl.java
components-api/src/main/java/org/talend/components/api/service/internal/osgi/ComponentServiceOsgi.java
components-api/src/main/java/org/talend/components/api/service/internal/spring/ComponentServiceSpring.java
components-common/src/main/java/org/talend/components/common/ProxyProperties.java
components-common/src/main/java/org/talend/components/common/SchemaProperties.java
components-common/src/main/java/org/talend/components/common/UserPasswordProperties.java
components-proptester/src/main/java/org/talend/components/proptester/PropertiesTester.java
components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceComponentTestIT.java
components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceTestBase.java
components-splunk/src/test/java/org/talend/components/splunk/TSplunkEventCollectorTestIT.java

made Component service handle Properties instead of ComponentProperties so that nested properties may be created as simple Properties, see *org.talend.components.common.SchemaProperties* for an example.

TCOMP-201 : made service callbacks work with Properties.

---

components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java

for "bulkfilepath"
https://jira.talendforge.org/browse/TUP-4833

TUP-4833: salesforceOutputBulkExec not properly closed by double quote

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SObjectAdapterFactory.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java

`Select Id, Name,(Select Id,Contact.Name from Contacts Limit 1) from Account Limit 10`
Fixed problem of nested query which is work in old framework.
("Account_Contacts_records_Name" or "Contacts_records_Name" should both return the value)
Just keep same with old framework.

TDI-36337: tSalesforceInput / Relationship fix problem of nested query

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java

https://jira.talendforge.org/browse/TUP-4370
1) Fixed "ceaseForError" doesn't work
2) Fixed batch mode

TUP-4370: Fixed issue about tSalesforceOutput

---

components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java

https://jira.talendforge.org/browse/TUP-4842

TUP-4842: tsalesforceOutputBulkExec issue when action is upsert

---

components-dataprep/src/main/java/org/talend/components/dataprep/connection/DataPrepConnectionHandler.java
components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepConnectionHandlerTest.java
components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepServerMock.java

* Adds &tag=components to create URL
* Adds unit test assertions for component URL (+ additions on mock server to actually check last request values).

TDP-2082: Adds ?tag=components to create dataset URL

---

components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceGetDeletedUpdatedProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceGetDeletedReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceGetDeletedUpdatedReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceGetUpdatedReader.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceGetDeletedUpdatedReaderTestIT.java

https://jira.talendforge.org/browse/TUP-4835

TUP-4835: tsalesforceGetUpdated&tsalesforceGetDeleted UI and runtime issue

---

components-common/src/main/java/org/talend/components/common/runtime/ProxyPropertiesRuntimeHelper.java
components-common/src/test/java/org/talend/components/common/runtime/ProxyPropertiesRuntimeHelperTest.java

This PR will do below:
1. Add a authenticator to socket proxy(to fix the problem of authentication dialog popup many times).
2. Restore proxy properties if "useProxy" property is false.

TDI-36128: Add a authenticator for the socket proxy.

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceGetDeletedUpdatedReaderTestIT.java

https://jira.talendforge.org/browse/TUP-4841
1)Avoid class cast issue
2)Fixed upsert key is null value issue
3)Fix "Ignore null" for update/upsert

TUP-4841: tsalesforceOutput upsert key column  type issue

---

components-common/src/main/java/org/talend/components/common/runtime/GenericAvroRegistry.java

https://jira.talendforge.org/browse/TUP-4570

TUP-4570: fix the long type converter issue

---

components-common/src/test/java/org/talend/components/common/runtime/BulkFileWriterTest.java

https://jira.talendforge.org/browse/TUP-4570
Conflicts:
components-common/src/test/java/org/talend/components/common/runtime/BulkFileWriterTest.java

TUP-4570: add a junit for the long type with empty string pattern

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceAvroRegistry.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceGetDeletedUpdatedReader.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceRuntime.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputProperties.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java

https://jira.talendforge.org/browse/TUP-4610
Note:1.Fixed output filed(not string) with string value
2.Add junit.

TUP-4610: SalesforceOuput can't write string value for not string field

---

components-api-service/src/test/java/org/talend/components/api/service/testcomponent/TestComponentDefinition.java
components-api/src/test/java/org/talend/components/api/service/testcomponent/TestComponentDefinition.java
components-dataprep/src/main/java/org/talend/components/dataprep/tdatasetinput/TDataSetInputDefinition.java
components-dataprep/src/main/java/org/talend/components/dataprep/tdatasetoutput/TDataSetOutputDefinition.java
components-jira/src/main/java/org/talend/components/jira/tjirainput/TJiraInputDefinition.java
components-jira/src/main/java/org/talend/components/jira/tjiraoutput/TJiraOutputDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulk/TSalesforceOutputBulkDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecDefinition.java
components-splunk/src/main/java/org/talend/components/splunk/TSplunkEventCollectorDefinition.java

https://jira.talendforge.org/browse/TCOMP-218

TCOMP-218: fix the return property type

---

components-salesforce/src/main/java/org/talend/components/salesforce/UpsertRelationTable.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkFileWriter.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java
components-salesforce/src/main/resources/org/talend/components/salesforce/UpsertRelationTable.properties
components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceRuntimeTestUtil.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkFileWriterTestIT.java

https://jira.talendforge.org/browse/TUP-4585
Note:Support lookup field null value update

TUP-4585: Backport TDI-35282 on new Framework

---

components-splunk/src/main/java/org/talend/components/splunk/TSplunkEventCollectorDefinition.java
components-splunk/src/main/java/org/talend/components/splunk/TSplunkEventCollectorProperties.java
components-splunk/src/main/java/org/talend/components/splunk/runtime/SplunkWriterResult.java
components-splunk/src/main/java/org/talend/components/splunk/runtime/TSplunkEventCollectorWriteOperation.java
components-splunk/src/main/java/org/talend/components/splunk/runtime/TSplunkEventCollectorWriter.java
components-splunk/src/test/java/org/talend/components/splunk/TSplunkEventCollectorTestIT.java
components-splunk/src/test/java/org/talend/components/splunk/runtime/TSplunkEventCollectorWriterTestIT.java

declaration part
https://jira.talendforge.org/browse/TDI-36651

TDI-36651: use Result instead of SplunkWriterResult in the generic

---

components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulk/TSalesforceOutputBulkDefinition.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecDefinition.java
components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceComponentTestIT.java

https://jira.talendforge.org/browse/TDI-36651

TDI-36651: adjust the return property for salesforce components

---

components-common/src/main/java/org/talend/components/common/runtime/GenericAvroRegistry.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecProperties.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputProperties.java

Related to 
https://jira.talendforge.org/browse/TCOMP-176
https://jira.talendforge.org/browse/TUP-4863

TCOMP-176 Removed DI specific constants usage from components

---

components-dataprep/src/main/java/org/talend/components/dataprep/connection/DataPrepConnectionHandler.java
components-dataprep/src/main/java/org/talend/components/dataprep/connection/DataPrepStreamMapper.java
components-dataprep/src/main/java/org/talend/components/dataprep/runtime/DataSetWriter.java
components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepConnectionHandlerTest.java
components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepServerMock.java
components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepStreamMapperTest.java
components-dataprep/src/test/resources/org/talend/components/dataprep/connection/dataset.json

Revert "TDI-36474: tDatasetOutput doesn't have any message to hint job fail"

---

components-common/src/main/java/org/talend/components/common/runtime/BulkFileWriter.java
components-salesforce/src/main/java/org/talend/components/salesforce/UpsertRelationTable.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java

https://jira.talendforge.org/browse/TUP-4570

TUP-4570: fix some bugs for salesforce component

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java

https://jira.talendforge.org/browse/TUP-4943

TUP-4943: Fixed feedback records issue when extend insert checked

---

components-dataprep/src/main/java/org/talend/components/dataprep/connection/DataPrepConnectionHandler.java
components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepServerMock.java

https://jira.talendforge.org/browse/TDI-36474

TDI-36474: tDatasetOutput doesn't have any message to hint  job fail

---

components-dataprep/src/main/java/org/talend/components/dataprep/runtime/DataSetWriter.java

nulls?)
https://jira.talendforge.org/browse/TDI-36730

TDI-36730: Live dataset on MySQL data all shifted in data prep (due to

---

components-dataprep/src/main/java/org/talend/components/dataprep/connection/DataPrepConnectionHandler.java
components-dataprep/src/main/java/org/talend/components/dataprep/runtime/DataSetReader.java
components-dataprep/src/main/java/org/talend/components/dataprep/runtime/DataSetSourceOrSink.java
components-dataprep/src/main/java/org/talend/components/dataprep/runtime/DataSetWriter.java
components-dataprep/src/main/java/org/talend/components/dataprep/runtime/RuntimeProperties.java
components-dataprep/src/main/java/org/talend/components/dataprep/tdatasetinput/TDataSetInputProperties.java
components-dataprep/src/main/java/org/talend/components/dataprep/tdatasetoutput/TDataSetOutputProperties.java
components-dataprep/src/main/resources/org/talend/components/dataprep/tdatasetinput/messages.properties
components-dataprep/src/main/resources/org/talend/components/dataprep/tdatasetoutput/messages.properties
components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepConnectionHandlerTest.java
components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepServerMock.java
components-dataprep/src/test/java/org/talend/components/dataprep/runtime/DataSetReaderTest.java
components-dataprep/src/test/java/org/talend/components/dataprep/runtime/DataSetWriterTest.java
components-dataprep/src/test/java/org/talend/components/dataprep/tdatasetinput/AfterFetchSchemaTest.java

https://jira.talendforge.org/browse/TDI-36685

TDI-36685: improve the error information

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
components-salesforce/src/test/java/org/talend/components/salesforce/SalesforceComponentTestIT.java

https://jira.talendforge.org/browse/TUP-4958

TUP-4958: salseforce soap API version issue when migration

---

components-dataprep/src/main/java/org/talend/components/dataprep/connection/DataPrepConnectionHandler.java
components-dataprep/src/main/java/org/talend/components/dataprep/tdatasetoutput/TDataSetOutputProperties.java
components-dataprep/src/test/java/org/talend/components/dataprep/connection/DataPrepServerMock.java

https://jira.talendforge.org/browse/TDI-36627

TDI-36627: fix the component part and fix a refresh issue

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceInputReader.java

https://jira.talendforge.org/browse/TUP-4964

TUP-4964: Field copy lost properties

---

components-dataprep/src/main/java/org/talend/components/dataprep/runtime/DataSetWriter.java

dataset
https://jira.talendforge.org/browse/TDI-36822

TDI-36822: NPE in tDatasetOutput when performing a full run on a live

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceAvroRegistry.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java

https://jira.talendforge.org/browse/TDI-36857

TDI-36857: Fixed bulk query null value convert issue

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceAvroRegistry.java
components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java

https://jira.talendforge.org/browse/TDI-36918

TDI-36918: Fix tSalesforceOutput write base64 type date issue

---

components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java

https://jira.talendforge.org/browse/TDI-37117

TDI-37117: Improve junit test "SalesforceWriterTestIT.testUploadAttachment"

---

components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceProxyTestIT.java

https://jira.talendforge.org/browse/TDI-36915

TDI-36915: apply the proxy setting for bulk connection

---

components-dataprep/src/main/java/org/talend/components/dataprep/tdatasetoutput/TDataSetOutputProperties.java
components-dataprep/src/main/resources/org/talend/components/dataprep/tdatasetoutput/messages.properties
components-dataprep/src/test/java/org/talend/components/dataprep/tdatasetinput/AfterFetchSchemaTest.java

label value
https://jira.talendforge.org/browse/TDI-36815

TDI-36815: 1. add a note when success to fetch. 2. add the miss i18

---

components-salesforce/pom.xml
components-salesforce/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java

https://jira.talendforge.org/browse/TDI-37028

TDI-37028 : Upgrade Salesforce API with latest one(should be >=37.0).

---

components-filedelimited/src/main/java/org/talend/components/filedelimited/runtime/DelimitedAdaptorFactory.java

The tFileInputDelimited re-initializes avro convert objects per-record when they can be reused for the entire job.
The tFileInputDelimited reuses these objects for the entire job.
Tests already exist.  I didn't find a JIRA for the performance issue.

components-filedelimited: Fix initialization code for avro converters.

---

components-salesforce/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java

SalesforceInputReaderTestIT.testManualQuery() may be useless in some account.
It's my misunderstand about field "LastViewedDate". When QA test the SOQL in their account.
They found is would useless in their account.
Do not use default records for test. Would created 2 records for this unit test

test (TDI-37630): improve the salesforce manual query test to avoid useless in some account

---

core/components-adapter-beam/pom.xml

We're using a SNAPSHOT API for Beam.
We're using a published, non-changing API for Beam.

TCOMP-279 Update Beam API version to stable 0.3.0-incubating

---

components-salesforce/src/test/java/org/talend/components/salesforce/test/SalesforceComponentTestIT.java

https://jira.talendforge.org/browse/TDI-37821
The plain salesforce IT tests are no longer running, saving 1/3 of the salesforce activity.

TDI-37821 Reduce Salesforce requests

---

components/components-processing/pom.xml
components/components-processing/processing-definition/pom.xml
components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/ProcessingFamilyDefinition.java
components/components-processing/processing-runtime/pom.xml
components/pom.xml

No module for components-processing.
Add "components-processing" module to have a base to add new components processing.
An example on that kind of component will be added soon.

Add structure for new components-processing

---

components/components-fileio/fileio-integration/src/test/java/org/talend/components/fileio/integration/SimpleFileIoDatasetRuntimeTest.java
components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIoOutputRuntimeTest.java
components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/test/MiniDfsResource.java
components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/test/MiniDfsResourceTest.java

https://jira.talendforge.org/browse/TCOMP-417

fix(TCOMP-417): Fixed tests failing on Windows dev env.

---

components/components-elasticsearch/elasticsearch-runtime_2_4/src/test/java/org/talend/components/elasticsearch/runtime_2_4/ElasticsearchBeamRuntimeTestIT.java
components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/test/MiniDfsResourceTest.java
components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/runtime/beam/JDBCBeamRuntimeTest.java
components/components-kafka/kafka-runtime/src/test/java/org/talend/components/kafka/runtime/KafkaAvroBeamRuntimeTestIT.java
components/components-kafka/kafka-runtime/src/test/java/org/talend/components/kafka/runtime/KafkaCsvBeamRuntimeTestIT.java
components/components-localio/localio-runtime/src/test/java/org/talend/components/localio/runtime/fixedflowinput/FixedFlowInputRuntimeTest.java
core/components-adapter-beam/src/test/java/org/talend/components/adapter/beam/io/rowgenerator/RowGeneratorIOTest.java
core/components-adapter-beam/src/test/java/org/talend/components/adapter/beam/transform/DirectCollectorTest.java
core/components-adapter-beam/src/test/java/org/talend/components/adapter/beam/transform/DirectConsumerCollectorTest.java

BEAM-1205 was merged last night and breaks current Beam unit tests.
Tests are no longer broken.

fix(BEAM-1205): Always use @Rule for TestPipeline.

---

components/components-salesforce/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
components/components-salesforce/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java

Fixed comments from previous review
https://jira.talendforge.org/browse/TDI-38220

bugfix(TDI-38220): Removed unnecessary constant, replaced default query

---

components-parent/components-p2update-assembly/pom.xml
components-parent/pom.xml
components/components-filterrow/pom.xml
components/components-salesforce/src/main/resources/README.md
examples/components-api-archetypes/input-component-archetype/src/main/resources/archetype-resources/pom.xml
examples/components-multiple-runtimes-and-deps/multiple-runtime-comp/pom.xml
examples/components-multiple-runtimes-and-deps/same_libs_with_2_versions/zeLib/pom.xml
examples/components-multiple-runtimes-and-deps/same_libs_with_2_versions/zeLib_v2/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp-runtime_v01/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp-runtime_v02/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp/pom.xml
services/components-api-service-rest/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [master]

---

components-api-archetypes/src/main/resources/archetype-resources/pom.xml
components-api-full-example/pom.xml
components-dataprep/pom.xml
components-jira/pom.xml
components-parent/pom.xml
components-salesforce/src/main/resources/README.md
components-splunk/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.13]

---

components-parent/components-p2update-assembly/pom.xml
components-parent/pom.xml
components-salesforce/src/main/resources/README.md
examples/components-api-archetypes/input-component-archetype/src/main/resources/archetype-resources/pom.xml
examples/components-multiple-runtimes-and-deps/multiple-runtime-comp/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp-runtime_v01/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp-runtime_v02/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp/pom.xml
services/components-api-service-rest/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.17]

---

components-api-archetypes/src/main/resources/archetype-resources/pom.xml
components-parent/pom.xml
components-salesforce/src/main/resources/README.md
examples/components-multiple-runtimes-and-deps/multiple-runtime-comp/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp-runtime_v01/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp-runtime_v02/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.15]

---

components-api/src/main/resources/archetype-resources/pom.xml
components-dataprep/pom.xml
components-jira/pom.xml
components-parent/pom.xml
components-salesforce/src/main/resources/README.md
components-splunk/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.8]

---

components-api/src/main/resources/archetype-resources/pom.xml
components-parent/pom.xml
components-salesforce/src/main/resources/README.md

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.5]

---

components-parent/pom.xml
components-salesforce/src/main/resources/README.md

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.4.0]

---

components-parent/pom.xml
components-salesforce/src/main/resources/README.md

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.1.0]

---

components-parent/pom.xml
components-salesforce/src/main/resources/README.md

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.2.0]

---

components-api-archetypes/src/main/resources/archetype-resources/pom.xml
components-parent/components-p2update-assembly/pom.xml
components-parent/pom.xml
components-salesforce/src/main/resources/README.md
examples/components-multiple-runtimes-and-deps/multiple-runtime-comp/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp-runtime_v01/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp-runtime_v02/pom.xml
examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp/pom.xml
services/components-api-service-rest/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/0.16]

---

components/components-azurestorage/src/main/java/org/talend/components/azurestorage/queue/runtime/AzureStorageQueueListReader.java

https://jira.talendforge.org/browse/TDI-38252

TDI-38252:tAzureStorageQueueList throws NPE when no queue exist

---

components-api-archetypes/src/main/resources/archetype-resources/pom.xml
components-api-full-example/pom.xml
components-dataprep/pom.xml
components-jira/pom.xml
components-parent/pom.xml
components-salesforce/src/main/resources/README.md
components-splunk/pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/6.2.1/TDI-38194]

---

components/components-snowflake/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java

DATE and TIME type will get the incorrect value through Dynamic
DATE and TIME type will get correct value through Dynamic
https://jira.talendforge.org/browse/TDI-38286

bugfix(TDI-38286): fix DATE and TIME type value through Dynamic

---

components/components-azurestorage/src/main/java/org/talend/components/azurestorage/queue/AzureStorageQueueDefinition.java

variable on tAzureStorageQueueList
https://jira.talendforge.org/browse/TDI-38251

TDI-38251:The default type shoule be Integer for number of queue

---

components/components-snowflake/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java

NPE in getConnectionUrl()
correct getConnectionUrl() method
https://jira.talendforge.org/browse/TDI-38392

fix(TDI-38392): fixed NPE in getConnectionUrl()

---

components/components-snowflake/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
components/components-snowflake/src/test/java/org/talend/components/snowflake/test/SnowflakeTestIT.java

When remove the @Ignore annotation test - case fails 
When account is null java.sql.SQLException: Missing user name thorws 
https://jira.talendforge.org/browse/TDI-38392

fix(TDI-38392): fix ignored testOutputBadConnection

---

components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/common/SalesforceErrorCodes.java
components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataset/SalesforceDatasetProperties.java
components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/datastore/SalesforceDatastoreProperties.java
components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/dataset/messages.properties
components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/dataset/SalesforceDatasetPropertiesTestIT.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDatastoreRuntime.java
components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDatasetRuntimeTestIT.java
components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/dataprep/SalesforceInputTestIT.java

Salesforce module nales uses "select" widget
Salesforce module nales uses "datalist" widget
Need https://github.com/Talend/daikon/pull/205/

feat(TDP-3329) : use "datalist" widget

---

components/components-snowflake/src/main/java/org/talend/components/snowflake/runtime/SnowflakeSourceOrSink.java
components/components-snowflake/src/test/java/org/talend/components/snowflake/runtime/SnowflakeSourceOrSinkTest.java

- [-] Tests for the changes have been added (for bug fixes / features)
NPE when connection is closed
Error message is more informative
- [] Yes
https://jira.talendforge.org/browse/TDI-38272

bugfix(TDI-38272) : fix NPE when connection is closed

---

components/components-snowflake/src/main/java/org/talend/components/snowflake/runtime/SnowflakeReader.java
components/components-snowflake/src/test/java/org/talend/components/snowflake/runtime/SnowflakeReaderTest.java

tSnowflakeInput -> Can't get NB_LINE value
tSnowflakeInput -> NB_LINE value is available
- [ x] No
https://jira.talendforge.org/browse/TDI-38307

bugfix(TDI-38307) : fix NB_LINE value in SnowflakeInput

---

components/components-netsuite/netsuite-definition/src/main/java/org/talend/components/netsuite/input/NetSuiteInputModuleProperties.java
components/components-netsuite/netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/search/SearchFieldOperatorTypeDesc.java

- After record type was selected it is not possible to add search condition due to an exception (https://jira.talendforge.org/browse/TDI-38452)
- After record type was selected it is possible to add search condition

bugfix(TDI-38452): Fixed updating of search conditions table

---

components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/runtime/AzureStorageTableWriter.java

https://jira.talendforge.org/browse/TDI-38300
the write(Object data) method in the output table receive Index record
type, so no need to do farther conversion

fix(TDI-38300): fix azure outputTable exception when main connector used

---

components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/dataprep/JDBCInputDefinition.java
components/components-jdbc/components-jdbc-definition/src/test/java/org/talend/components/jdbc/dataprep/JDBCInputDefinitionTest.java
components/components-processing/processing-definition/src/main/java/org/talend/components/processing/replicate/ReplicateDefinition.java
components/components-processing/processing-definition/src/main/java/org/talend/components/processing/window/WindowDefinition.java
components/components-processing/processing-definition/src/test/java/org/talend/components/processing/replicate/ReplicateDefinitionTest.java
components/components-processing/processing-definition/src/test/java/org/talend/components/processing/window/WindowDefinitionTest.java

No icons provided for DataPrepDBInput, Replicate and Window components
Icons available for DataPrepDBInput, Replicate and Window components

feat(TFD-838) add icons for missing components icons

---

components/components-marketo/src/main/java/org/talend/components/marketo/runtime/MarketoListOperationWriter.java
components/components-marketo/src/main/java/org/talend/components/marketo/runtime/client/MarketoSOAPClient.java
components/components-marketo/src/test/java/org/talend/components/marketo/runtime/client/MarketoSOAPClientTestIT.java

https://jira.talendforge.org/browse/TDI-38566
Fix mainly SOAP empty errors.

bugfix(TDI-38566) : Updated error management for list operations

---

components/components-fileio/pom.xml
components/components-fileio/s3-runtime-di/pom.xml
components/components-fileio/s3-runtime-di/src/main/java/org/talend/components/s3/runtime/S3Connection.java
components/components-fileio/s3-runtime-di/src/main/java/org/talend/components/s3/runtime/S3OutputWriter.java
components/components-fileio/s3-runtime-di/src/main/java/org/talend/components/s3/runtime/S3Sink.java
components/components-fileio/s3-runtime-di/src/main/java/org/talend/components/s3/runtime/S3SourceOrSink.java
components/components-fileio/s3-runtime-di/src/main/java/org/talend/components/s3/runtime/S3WriteOperation.java
components/components-fileio/s3-runtime-di/src/test/java/org/talend/components/s3/runtime/PropertiesPreparer.java
components/components-fileio/s3-runtime-di/src/test/java/org/talend/components/s3/runtime/S3SinkTestIT.java
components/components-fileio/s3-runtime-di/src/test/java/org/talend/components/s3/runtime/S3SourceOrSinkTestIT.java
components/components-fileio/s3-runtime-di/src/test/resources/log4j.properties
components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/SimpleFileIOComponentFamilyDefinition.java
components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/output/S3OutputDefinition.java
components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/s3/output/S3OutputDefinitionTest.java
services/components-api-service-rest-all-components/pom.xml

https://jira.talendforge.org/browse/TDI-38614

feat(TDI-38614): Add DI runtime for S3 component

---

components/components-salesforce/components-salesforce-definition/pom.xml
components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/OAthDepsTestIT.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/connection/oauth/SalesforceOAuthConnection.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/common/SalesforceRuntimeCommon.java

https://jira.talendforge.org/browse/TDI-38939
This PR solve the class loader problem in salesforce bundle
and provide better error handling

fix(tdi-38939): salesforce oauth error enhancement

---

components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceAvroRegistry.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/SalesforceAvroRegistryTest.java

This reverts commit 53eeb5f6e432549a9c519ab78b3683e626d09a83.
This is a revert for https://github.com/Talend/components/commit/53eeb5f6e432549a9c519ab78b3683e626d09a83
to roll back changes made after enforcers update
https://jira.talendforge.org/browse/TDI-39192

Revert "fix(TDI-39124): first part of fix for new data flow (#882)"

---

services/components-api-service-rest-all-components/readme.md

Update readme of `components-api-service-rest-all-components`

---

components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/MarketoComponentDefinition.java
components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketobulkexec/TMarketoBulkExecDefinition.java
components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketoinput/TMarketoInputProperties.java
components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketooutput/TMarketoOutputProperties.java

https://jira.talendforge.org/browse/TDI-38416

fix(TDI-38416): Runtime problems

---

components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/window/WindowDefinition.java

the component Window cannot be instantiated by the spark job server.
Fix the instantiation.

bug(TFD-2368): Fix Window Path instanciation.

---

components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3OutputRuntime.java

When overwriting a directory in S3, the AWS credentials are not used.
When overwriting a directory in S3, the AWS credentials are included in the filesystem request.

fix(TFD-2364): Use the correct permissions for overwriting in S3.

---

components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/BulkResult.java

https://jira.talendforge.org/browse/TDI-39501
make SOQL in salesforce case insensitive.

fix(TDI-39501): make SOQL in salesforce case insensitive.

---

components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/BulkResultSet.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSource.java
components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDatasetRuntimeTestIT.java

https://jira.talendforge.org/browse/TDI-39500
add support of SOQL Relationship queries
Need to be merged only after #985

fix(TDI-39500) : add support of SOQL Relationship queries

---

components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/client/MarketoLeadClient.java

See https://github.com/Talend/components/pull/1022

fix(TDI-39322): fix incorrect paging on leads Backport to 651

---

components/components-marketo/src/main/java/org/talend/components/marketo/runtime/client/MarketoLeadClient.java

See https://github.com/Talend/components/pull/1022

fix(TDI-39322): fix incorrect paging on leads Backport to 641

---

components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/MarketoConstants.java
components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/MarketoUtils.java
components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/MarketoUtilsTest.java
components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/MarketoSourceTest.java

https://jira.talendforge.org/browse/TDI-39784
Add Customer's date format to allowed date patterns

fix(TDI-39784): 

---

components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/MarketoConstants.java
components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/MarketoUtils.java
components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/MarketoUtilsTest.java
components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/client/MarketoSOAPClient.java
components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/MarketoSourceTest.java

https://jira.talendforge.org/browse/TDI-39784
Fix NPE in some cases, correct field mappings in SOAP Leads

 fix(TDI-39784): add guard to SOAP attributes to protect from NPE

---

components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/CommonUtils.java
components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/dataset/JDBCDatasetProperties.java
components/components-jdbc/components-jdbc-definition/src/test/java/org/talend/components/jdbc/dataset/JDBCDatasetPropertiesTest.java

https://jira.talendforge.org/browse/TCOMP-696
we will validate the sql if a query

fix(TCOMP-696): Protect from SQL injection in TCOMP/JDBC component

---

components-parent/pom.xml
components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/SalesforceConnectionWizardDefinitionTest.java
components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/SalesforceModuleWizardDefinitionTest.java
components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/test/SalesforceConnectionPropertiesTest.java
components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputPropertiesTest.java

https://jira.talendforge.org/browse/TDI-39544
fix the migration task
same as https://github.com/Talend/components/pull/1048
this branch is created to build using daikon fix from https://github.com/Talend/daikon/pull/313

fix(TDI-39544)/fix(TDKN-190) Import salesforce with oauth type can't show my value

---

components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceDefinition.java
components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecDefinition.java
components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecDefinitionTest.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.java

https://jira.talendforge.org/browse/TDI-39873

fix(TDI-39873):  implement tSalesforceBulkExec ComponentDriverInitialization

---

components/components-snowflake/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRowWriter.java

https://jira.talendforge.org/browse/TDI-39881
Add call to setAutoCommit(false).

fix(TDI-39881): implement correct commit usage

---

components/components-netsuite/components-netsuite-runtime/pom.xml
components/components-netsuite/components-netsuite-runtime_2014_2/pom.xml
components/components-netsuite/components-netsuite-runtime_2016_2/pom.xml

https://jira.talendforge.org/browse/TDI-39827
Upgrade to CXF 3.2.1

feat(TDI-39827): Netsuite components upgrade to CXF 3.2.1

---

components/components-couchbase/src/main/java/org/talend/components/couchbase/CouchbaseDefinition.java

https://jira.talendforge.org/browse/TDI-39972

fix(TDI-39972):move couchbase to Databases NoSQL

---

components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java
components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/tsalesforceinput/messages.properties
components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputPropertiesTest.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java

https://jira.talendforge.org/browse/TDI-40149
User can define a timeout  for the salesforce job or disabled it with 0.

fix(TDI-40149) : salesforce long running query master

---

components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCConnectionTestIT.java

https://jira.talendforge.org/browse/TDI-40299
https://jira.talendforge.org/browse/TDI-40299

fix(TUP-19789): NPE error occurred in error log when check "Test connect" button with no any input  connection parameters

---

services/components-api-service-rest-all-components/pom.xml
services/components-api-service-rest/pom.xml

Docker image version is aligned with our new policy.
Build / CI related changes.
See: https://jira.talendforge.org/browse/DEVOPS-5343
No.

Align Docker image version with policy

---

services/components-api-service-rest-all-components/pom.xml
services/components-api-service-rest/pom.xml

Docker base image has not fixed version, so latest image is used up to production
Docker base image will have a fixed version coming from the result of microservices-base CI build job.

fix microservices base image version

---

services/components-api-service-rest/src/test/resources/application.properties

https://jira.talendforge.org/browse/TCOMP-942
Properties configuration file has been added.

fix(TCOMP-942) : Add bootstrap propeties conf file

---

components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/JdbcRuntimeInfo.java

UNEXPECTED_EXCEPTION
- [ *] The commit message follows Talend standard
- [*] Bugfix
- [ *] No

bugfix(TUP-21973):Job migrated from 6.5.1 to 7.1.1 throwing

---

components-parent/components-bom/pom.xml
components-parent/pom.xml

feat(TDI-41787): Upgrade to CXF 3.3.1

---

components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/schemainfer/SchemaInferer.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/JDBCMapping.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/RowWriter.java
components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCInputTestIT.java
components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/common/DBTestUtils.java
components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/type/JDBCTypeMappingTestIT.java
core/components-common/src/main/java/org/talend/components/common/avro/JDBCAvroRegistry.java

https://jira.talendforge.org/browse/TDI-42747
https://jira.talendforge.org/browse/TDI-42747

fix(TDI-42747): tJDBCOutput does not work with BLOB dataType

---

components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRowStandalone.java

operations on a closed resultSet
operations on an open resultSet

fix(TDI-42686): fix "doing operations on a closed result set"

---

components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcoutput/messages.properties
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/DebugUtil.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/RowWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputDeleteWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertOrUpdateWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateOrInsertWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateWriter.java

https://jira.talendforge.org/browse/TDI-34953

Fix(TDI-34953):Enable tJDBCOutput print sql.

---

components-parent/components-bom/pom.xml
components-parent/pom.xml

feat(TDI-43088): Update cxf dep for tcompv0

---

components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/TextJacksonJsonProvider.java

Use new name for removed method

fix(TDI-43085): Fix hadoop compile error

---

components/components-hadoopcluster/hadoopcluster-runtime/pom.xml
components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/TextJacksonJsonProvider.java

https://jira.talendforge.org/browse/TUP-25202

Fix TUP-25202 can't get ambari configuration when I select retrieve it from job server

---

components-parent/components-bom/pom.xml
components/components-marklogic/components-marklogic-runtime/pom.xml

for jira: https://jira.talendforge.org/browse/TDI-43395
update dom4j to 2.1.1

feat(TDI-43395):update dom4j to 2.1.1

---

services/components-maven-repo/config/jdbc_config.json
services/components-maven-repo/pom.xml

https://jira.talendforge.org/browse/TDI-43509
https://jira.talendforge.org/browse/TDI-43509

fix(TDI-43509): Upgrade redshift driver

---

components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeConnectionPropertiesTest.java

https://jira.talendforge.org/browse/TDI-43092

fix(TDI-43092):fix junit test.

---

components-parent/components-bom/pom.xml
services/components-api-service-rest-all-components/pom.xml
services/components-api-service-rest/pom.xml

https://jira.talendforge.org/browse/TDI-43723
I also removed a duplicate dependency declaration to fix a maven build warning.

TDI-43723 - Updating Commons Beanutils + Xerces

---

components/components-marklogic/components-marklogic-runtime/pom.xml

https://jira.talendforge.org/browse/DEVOPS-10102
Replace official marklogic repo by proxy repo setup by devops

bugfix(DEVOPS-10102): Replace marklogic repo with proxy repo

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-44192
https://jira.talendforge.org/browse/TDI-44192

fix(TDI-44192): Update dom4j to 2.1.3

---

ci/Jenkinsfile-scan

TDI-44227 : veracode

---

components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/JdbcRuntimeSourceOrSinkDefault.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCCloseSourceOrSink.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCCommitSourceOrSink.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRollbackSourceOrSink.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRowSourceOrSink.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSPSourceOrSink.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCRowReader.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCSPReader.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCRowWriter.java

https://jira.talendforge.org/browse/TDI-45146

fix(TDI-45146):Add debug message

---

components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java

https://jira.talendforge.org/browse/TDI-45011
Backport of https://github.com/Talend/components/pull/1787 into "maintenance/0.28" branch.

fix(TDI-45011): BP_0.28 NetSuite TCompV0: set mappings for transaction custom body fields.

---

components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java

https://jira.talendforge.org/browse/TDI-45011

fix(TDI-45011): NetSuite TCompV0: set mappings for transaction custom body fields.

---

components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java

https://jira.talendforge.org/browse/TDI-45011
Backport of https://github.com/Talend/components/pull/1787 into "maintenance/0.27" branch

fix(TDI-45011): BP_0.27 NetSuite TCompv0 : set mappings for transaction custom body fields.

---

components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java

https://jira.talendforge.org/browse/TDI-45322

fix(TDI-45322): NetSuite TComp 0.28 - add mapping for Inventory Transfer transaction

---

components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java

https://jira.talendforge.org/browse/TDI-45322
Backport of https://github.com/Talend/components/pull/1808 into "master" branch.

fix(TDI-45322): BP_Master NetSuite TCompV0: add mapping for Inventory Transfer transaction

---

components/components-hadoopcluster/hadoopcluster-runtime/pom.xml

chore(TUP-29396): add exclusion from hadoop-core

---

components/components-hadoopcluster/hadoopcluster-runtime/pom.xml

chore(TUP-29386): exclusion jetty

---

components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/JDBCSQLBuilder.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/RowWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputDeleteWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertOrUpdateWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateOrInsertWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateWriter.java
components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCOutputTestIT.java
components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/common/DBTestUtils.java

https://jira.talendforge.org/browse/TDI-45265
https://jira.talendforge.org/browse/TDI-45265

fix(TDI-45265): Dynamic type with Delta lake

---

components-parent/components-bom/pom.xml
services/components-api-service-rest/pom.xml

https://jira.talendforge.org/browse/TDI-45356

fix(TDI-45356): Align version of "httpclient" and "httpcore" dependencies.

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-45356
Backport of https://github.com/Talend/components/pull/1823 into "master" branch.

fix(TDI-45356): BP: Align version of "httpclient" and "httpcore" dependencies.

---

components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/SalesforceSessionReuseTestIT.java

Basically in the test there is a new instance of the exception class and a message assertion. The message is hardcoded inside as is in other tests.

fix(TDI-36042):Firendly message for Salesforce TEST FIX

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-45489
Backport of https://github.com/Talend/components/pull/1640 into "maintenance/0.28" branch.

fix(TDI-45489): Components - update nimbus-jose-jwt

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-45447

fix(TDI-45447): Upgrade bouncycastle

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-45436

fix(TDI-45436):upgrade xstream

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-45418

fix(TDI-45418):Upgrade Jackson libraries

---

core/components-api/src/main/java/org/talend/components/api/component/runtime/JarRuntimeInfo.java
core/components-api/src/test/java/org/talend/components/api/component/runtime/JarRuntimeInfoTest.java

feat(TUP-29701): Upgrade eclipse 418

---

components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceBulkProperties.java
components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/SalesforceBulkProperties.properties
components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReaderTestIT.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReader.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkV2ExecReader.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkV2Runtime.java

For feature: https://jira.talendforge.org/browse/TDI-42274

feat(TDI-42274):Add Safety Switch checkbox for tSalesforceOutputBulkExec

---

components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutput/TJDBCOutputProperties.java

https://jira.talendforge.org/browse/TDI-45505
https://jira.talendforge.org/browse/TDI-45505

fix(TDI-45505): "useDataSource" property is not processed by tJDBCOutput correctly

---

components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/runtime/AzureStorageContainerRuntime.java
components/components-azurestorage/src/test/java/org/talend/components/azurestorage/blob/runtime/AzureStorageContainerRuntimeTest.java

fix(TDI-45593): Do not throw error when container name is numerical

---

components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/NsObjectTransducer.java
components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/ListOrRecord.java
components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/MultiSelectCustomField.java

https://jira.talendforge.org/browse/TDI-45495
Fix multi select field support.

fix(TDI-45495): backport fix to tcomp

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-45655

fix(TDI-45727): CVE jackson-mapper-asl

---

components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/output/NsObjectOutputTransducer.java
components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/AbstractNetSuiteTestBase.java
components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/output/NetSuiteOutputTransducerTest.java
components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/test/TestUtils.java
components/components-netsuite/components-netsuite-runtime/src/test/resources/test-data/customTransaction-1.json

https://jira.talendforge.org/browse/TDI-45899

fix(TDI-45899): Delete custom transactional record.

---

components-parent/components-bom/pom.xml

fix(TDI-45824): Bump jersey for tcompv0

---

components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIOAvroRegistry.java
components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIODatasetRuntime.java
components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIOInputRuntime.java
components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleRecordFormatCsvIO.java
components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleRecordFormatExcelIO.java
components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/ConfigurableHDFSFileSource.java
components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/csv/CSVFileInputFormat.java
components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/csv/CSVFileRecordReader.java
components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3InputRuntime.java
components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sources/UgiFileSourceBase.java
components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/ExtractCsvRecordTest.java
components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIOInputErrorTest.java
components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIOInputRuntimeTest.java
components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/gs/GSRoundTripRuntimeTestIT.java

https://jira.talendforge.org/browse/TDI-45852

fix(TDI-45852):fileIO support header for read

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-46109

fix(TDI-46109): update XStream to 1.4.17

---

components/components-marklogic/components-marklogic-runtime/pom.xml

https://jira.talendforge.org/browse/TDI-46766

chore(TDI-46766): add "JCenter" repo for Marklogic.

---

components/components-marklogic/components-marklogic-runtime/pom.xml

https://jira.talendforge.org/browse/TDI-46766

chore(TDI-46766): https connection for JCenter.

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-46614

fix(TDI-46614): CVE - update "commons-compress" to 1.21

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-46756

fix(TDI-46756): update XStream to 1.4.18

---

components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/query/EDatabaseTypeName.java

https://jira.talendforge.org/browse/TDI-44682

TDI-44682 - Fix some locale issues

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-46887

fix(TDI-46887): CVE - update "jena-core" to 4.2.0

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-46753

fix(TDI-46753) CVE - update "glassfish-jersey" dependencies to 2.33

---

components-parent/components-bom/pom.xml
components/components-marklogic/components-marklogic-runtime/pom.xml

https://jira.talendforge.org/browse/TDI-46746
Backport of https://github.com/Talend/components/pull/1966 into "maintenance/8.0" branch.

fix(TDI-46746): backport for branch "maintenance/8.0"

---

components-parent/components-bom/pom.xml
components/components-marklogic/components-marklogic-runtime/pom.xml

https://jira.talendforge.org/browse/TDI-46746
Backport of https://github.com/Talend/components/pull/1966 into "maintenance/7.3" branch.

fix(TDI-46746): backport for branch "maintenance/7.3"

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-46753
Backport of https://github.com/Talend/components/pull/1981 into "maintenance/8.0" branch.

fix(TDI-46753): backport to "maintenance/8.0" branch

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-46753
Backport of https://github.com/Talend/components/pull/1981 into "maintenance/7.3" branch.

fix(TDI-46753): backport to "maintenance/7.3" branch

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-46887
Backport of https://github.com/Talend/components/pull/1982 into "maintenance/8.0" branch.

fix(TDI-46887): backport to "maintenance/8.0" branch.

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-47269
Backport of https://github.com/Talend/components/pull/1982 into "maintenance/7.3" branch.

fix(TDI-47269): CVE - update "jena-core" to 4.2.0

---

components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveUtils.java

https://jira.talendforge.org/browse/TDI-46964

feat(TDI-46964): Request retry mechanism for Google Drive.

---

components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveUtils.java

https://jira.talendforge.org/browse/TDI-46964
Backport of https://github.com/Talend/components/pull/2004 into "maintenance/8.0" branch.

feat(TDI-46964): BP_801: Request retry mechanism for Google Drive.

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-47532

fix(TDI-47532): bump XercesImpl library to 2.12.2

---

components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeTypes.java

Added CHAR type to Snowflake types

fix(TDI-47772): Snowflake CHAR precision error when create table action

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-47935

fix(TDI-47935): bump "nimbus-jose-jwt" lib to fix CVE.

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-48134
Backport of https://github.com/Talend/components/pull/2079 into "maintenance/7.3" branch.

chore(TDI-48134): bump "nimbus-jose" version.

---

components/components-couchbase/pom.xml
components/components-couchbase/src/test/java/org/talend/components/couchbase/runtime/CouchbaseEventGenericRecordConverterTest.java

https://jira.talendforge.org/browse/TDI-48167
Backport of https://github.com/Talend/components/pull/2083 into "maintenance/7.3" branch.

fix(TDI-48167): CVE issue for Couchbase core-io.

---

components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/get/GoogleDriveGetDefinition.java
components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveGetReader.java
components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveGetRuntime.java
components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveUtils.java
components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/utils/GoogleDriveGetParameters.java
components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/utils/GoogleDriveGetParametersTest.java

https://jira.talendforge.org/browse/TDI-48093

fix(TDI-48093): Allow GoogleDrive component to work with large files.

---

ci/Jenkinsfile

Update Slack notifications following https://jira.talendforge.org/browse/TDI-47867

(chore) TDI-47867 Improve CI build visibility

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-48345
Backport of https://github.com/Talend/components/pull/2040 into "maintenance/8.0" branch.

fix(TDI-48345): bump XercesImpl library to 2.12.2

---

components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveUtils.java

https://jira.talendforge.org/browse/TDI-48417

fix(TDI-48417): skip useless caching operation for GoogleDrive.

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-48307
Backport of https://github.com/Talend/components/pull/2111 into "maintenance/8.0" branch.

fix(TDI-48307): BP_801: CVE on Jetty-io library.

---

components-parent/components-bom/pom.xml

overwrite version of aws-java-sdk-* libs

feat(TDI-47508): aws-java-sdk to bundle and CVE update

---

components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/connection/oauth/SalesforceImplicitConnection.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryV2Reader.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkV2ExecReader.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceReader.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceServerTimeStampReader.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/BulkV2Connection.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkQueryV2Runtime.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkV2Runtime.java
components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceSchemaUtils.java

https://jira.talendforge.org/browse/TDI-48546
https://jira.talendforge.org/browse/TDI-48546

fix(TDI-48546): tSalesforceOutput component throws java.lang.StringIndexOutOfBoundsException when the Parallelization is enabled

---

components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveAbstractListReader.java
components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveUtils.java
components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCopyReaderTest.java
components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCopyRuntimeTest.java

https://jira.talendforge.org/browse/TDI-48407

fix(TDI-48407): Fix search on a shared resources.

---

components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveAbstractListReader.java
components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveUtils.java
components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCopyReaderTest.java
components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCopyRuntimeTest.java

https://jira.talendforge.org/browse/TDI-48407
Backport of https://github.com/Talend/components/pull/2129 into "maintenance/8.0" branch.

fix(TDI-48407): BP_801: Fix search on a shared resources.

---

components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveAbstractListReader.java
components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveUtils.java
components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCopyReaderTest.java
components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCopyRuntimeTest.java

https://jira.talendforge.org/browse/TPS-5356
Backport of https://github.com/Talend/components/pull/2129 into "maintenance/7.3" branch.

fix(TPS-5356): Fix search on a shared resources.

---

components/components-hadoopcluster/hadoopcluster-runtime/pom.xml

chore(TUP-37210): CVE-2022-40149,org.codehaus.jettison:jettison:1.1

---

components-bom/pom.xml
components/components-azure-dls-gen2-blob/pom.xml
components/components-fileio/s3-runtime-di/pom.xml
components/components-fileio/simplefileio-runtime/pom.xml
components/components-jdbc/components-jdbc-runtime/pom.xml
components/components-salesforce/components-salesforce-runtime/pom.xml

fix(TDP-11800): force commons-text dependency because of CVE

---

services/pom.xml

chore(TDP-12515):  bump tsbi version to 0.0.19

---

services/components-maven-repo/pom.xml

chore(TDP-12582): exclude io.netty:netty

---

components-parent/components-bom/pom.xml

https://jira.talendforge.org/browse/TDI-50450

fix(TDI-50450): CVE upgrade snappy-java to 1.1.10.5

---

components-parent/components-bom/pom.xml
components/components-azurestorage/pom.xml

https://jira.talendforge.org/browse/TDI-50429

fix(TDI-50429): netty-codec-http2:4.1.97.Final | CVE-2023-44487

---

components-parent/components-bom/pom.xml
components/components-azurestorage/pom.xml

https://jira.talendforge.org/browse/TDI-50429

fix(TDI-50429): netty-codec-http2:4.1.86.Final | CVE-2023-44487
